import { type NextPage } from "next";
import Head from "next/head";
import { useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import { type RouterOptions } from "next/dist/server/router";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
dayjs.extend(relativeTime);
const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;

  return (<div className="flex gap-3">
    <img src={user.profileImageUrl} alt="Profile image" className="w-14 h-14 rounded-full"></img>
    <input placeholder="Type som emojis!" className="grow outline-none bg-transparent" />
  </div>)
};

type PostWithUser = RouterOptions['posts']['getAll']['number'];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div key={post.id} className="boder-b border-slate-400 p-8">
      <img src={author.profileImageUrl} alt="Profile image" className="w-14 h-14 rounded-full"></img>
      <div className="flex flex-col">
        <div>
          <span className="font-bold">{`@${author?.username}`}</span>
          <span className="text-slate-500">{` · ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>

        <span>
          {post.content}
        </span>
      </div>
    </div>
  )

}

const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (!data || isLoading) return <div>loading...</div>;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x md:max-w-2xl border-slate-400 ">
          <div>
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div>
            {[...data, ...data]?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>

          <div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
