# .github/workflows/keep_alive.yml

name: Keep alive cron job
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DATABASE_URL: 'mysql://4e7thhtr2qns8z3ro9q0:pscale_pw_6CnbJHcQR1bXPxkfsdU4fIYWLe2RJu1TQIgRSrdCmmm@aws.connect.psdb.cloud/chirpdb?sslaccept=strict'

jobs:
  cron:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install ts-node

      - name: Print secrets
        run: echo "DATABASE_URL=$DATABASE_URL"

      - name: Call endpoint to keep the database
        run: npm run keep-db-alive