# .github/workflows/keep_alive.yml

name: Keep alive cron job
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Call endpoint to keep the database
        run: npm run keep-db-alive