# .github/workflows/keep_alive.yml

name: Keep alive cron job
on: push
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint to keep the database alive
        run: npm run keep-db-alive