# .github/workflows/keep_alive.yml

name: Keep alive cron job
on:
  schedule:
    - cron: '0 * * * *'

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install ts-node

      - name: Call endpoint to keep the database
        run: npm run keep-db-alive