# .github/workflows/keep_alive.yml

name: Keep alive cron job
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install ts-node

      - name: Print secrets
        run: echo "DATABASE_URL=$DATABASE_URL"

      - name: Call endpoint to keep the database
        run: npm run keep-db-alive